// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PremiumUnit.Data;

#nullable disable

namespace PremiumUnit.Migrations
{
    [DbContext(typeof(PremiumUnitContext))]
    [Migration("20250228120034_AddForeignKeyToInvoice")]
    partial class AddForeignKeyToInvoice
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("PremiumUnit.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PenaltyBaseDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkshopCode")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WorkshopCode1")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkshopCode1");

                    b.ToTable("Invoice");
                });

            modelBuilder.Entity("PremiumUnit.Models.Workshop", b =>
                {
                    b.Property<int>("WorkshopCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ActivityStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployerPhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("ListSubmissionInterval")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Premium")
                        .HasColumnType("TEXT");

                    b.Property<int>("TypeOfActivity")
                        .HasColumnType("INTEGER");

                    b.HasKey("WorkshopCode");

                    b.ToTable("Workshop");
                });

            modelBuilder.Entity("PremiumUnit.Models.Invoice", b =>
                {
                    b.HasOne("PremiumUnit.Models.Workshop", null)
                        .WithMany("Invoices")
                        .HasForeignKey("WorkshopCode1");
                });

            modelBuilder.Entity("PremiumUnit.Models.Workshop", b =>
                {
                    b.Navigation("Invoices");
                });
#pragma warning restore 612, 618
        }
    }
}
